umb_virtual_apps:
    resource: "@UMBVirtualAppsBundle/Resources/config/routing.yml"
    prefix:   /

dmw_demo:
    resource: "@DMWDemoBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
articulo:
  pattern: /articulo/{id}
  defaults: { _controller: DMWDemoBundle:Default:articulo }
articulo_crear:
  pattern:  /articulos/crear
  defaults: { _controller: DMWDemoBundle:Articulos:crear }
articulo_editar:
  pattern:  /articulos/editar/{id}
  defaults: { _controller: DMWDemoBundle:Articulos:editar }
articulo_visualizar:
  pattern:  /articulos/visualizar/{id}
  defaults: { _controller: DMWDemoBundle:Articulos:visualizar }
articulo_borrar:
  pattern:  /articulos/borrar/{id}
  defaults: { _controller: DMWDemoBundle:Articulos:borrar }
articulo_new:
   pattern: /articulos/new
   defaults: { _controller: DMWDemoBundle:Articulos:new }
articulo_listar:
   pattern:  /articulos/listar
   defaults: { _controller: DMWDemoBundle:Articulos:listar }
articulos:
   pattern: /articulos/mostrar
   defaults: { _controller: DMWDemoBundle:Default:articulos }
ver_articulos:
    pattern:  /ver-articulos
    defaults: { _controller: DMWDemoBundle:Articulos:verArticulos }
DMWDemoBundle_noticias:
    pattern:  /noticias
    defaults: { _controller: DMWDemoBundle:Notice:index }
DMWDemoBundle_noticeView:
    pattern:  /leerNoticia/{notice_id}
    defaults: { _controller: DMWDemoBundle:Notice:noticeView }
DMWDemoBundle_pdf:
    pattern:  /pdf
    defaults: { _controller: DMWDemoBundle:Articulos:pdf}
