parameters:
#    umb_virtual_apps.example.class: UMBVirtual\AppsBundle\Example

services:
#    umb_virtual_apps.example:
#        class: %umb_virtual_apps.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
